apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"prometheus-to-sd","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"prometheus-to-sd"}},"template":{"metadata":{"labels":{"k8s-app":"prometheus-to-sd"}},"spec":{"containers":[{"command":["/monitor","--source=kube-proxy:http://localhost:10249?whitelisted=sync_proxy_rules_latency_microseconds\u0026metricsPrefix=container.googleapis.com/internal/addons","--source=kubelet:http://localhost:10255?whitelisted=kubelet_docker_operations,kubelet_docker_operations_errors,kubelet_runtime_operations,kubelet_runtime_operations_errors,kubelet_runtime_operations_latency_microseconds,kubelet_pleg_relist_latency_microseconds,kubelet_pod_start_latency_microseconds,rest_client_requests_total,storage_operation_duration_seconds,storage_operation_errors_total,run_podsandbox_duration_seconds,run_podsandbox_errors_total","--stackdriver-prefix=container.googleapis.com/internal/nodes","--api-override=https://monitoring.googleapis.com/"],"image":"k8s.gcr.io/prometheus-to-sd:v0.5.0","imagePullPolicy":"IfNotPresent","name":"prometheus-to-sd","resources":{"limits":{"cpu":"3m","memory":"20Mi"},"requests":{"cpu":"1m","memory":"20Mi"}}}],"hostNetwork":true,"nodeSelector":{"beta.kubernetes.io/os":"linux"},"priorityClassName":"system-node-critical","serviceAccountName":"prometheus-to-sd","tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"}]}}}}
  creationTimestamp: 2019-09-09T19:22:17Z
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: prometheus-to-sd
  namespace: kube-system
  resourceVersion: "663"
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/prometheus-to-sd
  uid: 232f5070-d337-11e9-b9e0-42010a800156
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: prometheus-to-sd
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: prometheus-to-sd
    spec:
      containers:
      - command:
        - /monitor
        - --source=kube-proxy:http://localhost:10249?whitelisted=sync_proxy_rules_latency_microseconds&metricsPrefix=container.googleapis.com/internal/addons
        - --source=kubelet:http://localhost:10255?whitelisted=kubelet_docker_operations,kubelet_docker_operations_errors,kubelet_runtime_operations,kubelet_runtime_operations_errors,kubelet_runtime_operations_latency_microseconds,kubelet_pleg_relist_latency_microseconds,kubelet_pod_start_latency_microseconds,rest_client_requests_total,storage_operation_duration_seconds,storage_operation_errors_total,run_podsandbox_duration_seconds,run_podsandbox_errors_total
        - --stackdriver-prefix=container.googleapis.com/internal/nodes
        - --api-override=https://monitoring.googleapis.com/
        image: k8s.gcr.io/prometheus-to-sd:v0.5.0
        imagePullPolicy: IfNotPresent
        name: prometheus-to-sd
        resources:
          limits:
            cpu: 3m
            memory: 20Mi
          requests:
            cpu: 1m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-to-sd
      serviceAccountName: prometheus-to-sd
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
  observedGeneration: 1
  updatedNumberScheduled: 2
